# alsatplg
# Autogenerated from man page /usr/share/man/man1/alsatplg.1.gz
complete -c alsatplg -s h -l help --description 'this help.'
complete -c alsatplg -s c -l compile --description 'source configuration file for the compilation.'
complete -c alsatplg -s o -l output --description 'output binary file.'
complete -c alsatplg -s v -l verbose --description 'set verbose level.'

