# festival_client
# Autogenerated from man page /usr/share/man/man1/festival_client.1.gz
complete -c festival_client -l server --description 'hostname (or IP number) of server.'
complete -c festival_client -l port --description 'port number of server process (1314).'
complete -c festival_client -l output --description 'file to save output waveform to.'
complete -c festival_client -l otype --description 'output type for waveform.'
complete -c festival_client -l passwd --description 'server passwd in plain text (optional).'
complete -c festival_client -l prolog --description 'filename containing commands to be sent  to the server before standard comman…'
complete -c festival_client -l async --description 'Asynchronous mode, server may send back  multiple waveforms per text file.'
complete -c festival_client -l ttw --description 'Text to waveform: take text from first  arg or stdin get server to return  wa…'
complete -c festival_client -l withlisp --description 'Output lisp replies from server.'
complete -c festival_client -l tts_mode --description 'TTS mode for file (default is fundamental).'
complete -c festival_client -l aucommand --description 'command to be applied to each  waveform retruned from server.'

