# festival
# Autogenerated from man page /usr/share/man/man1/festival.1.gz
complete -c festival -s q --description 'Load no default setup files.'
complete -c festival -l datadir --description 'Set data directory pathname.'
complete -c festival -l libdir --description 'Set library directory pathname.'
complete -c festival -s b --description 'Run in batch mode (no interaction).'
complete -c festival -l batch --description 'Run in batch mode (no interaction).'
complete -c festival -l tts --description 'Synthesize text in files as speech  no files means read from stdin  (implies …'
complete -c festival -s i --description 'Run in interactive mode (default).'
complete -c festival -l interactive --description 'Run in interactive mode (default).'
complete -c festival -l pipe --description 'Run in pipe mode, reading commands from  stdin, but no prompt or return value…'
complete -c festival -l language --description 'Run in named language, default is  english, spanish, russian, welsh and other…'
complete -c festival -l server --description 'Run in server mode waiting for clients  of server_port (1314).'
complete -c festival -l script --description '<ifile>  Used in #! scripts, runs in batch mode on  file and passes all other…'
complete -c festival -l heap --description 'Set size of Lisp heap, should not normally need  to be changed from its defau…'
complete -c festival -s v --description 'Display version number and exit.'
complete -c festival -l version --description 'Display version number and exit .'

