# pinout
# Autogenerated from man page /usr/share/man/man1/pinout.1.gz
complete -c pinout -s h -l help --description 'show this help message and exit.'
complete -c pinout -s r -l revision --description 'RPi revision.  Default is to autodetect revision of current device.'
complete -c pinout -s c -l color --description 'Force colored output (by default, the output will include ANSI color codes if…'
complete -c pinout -s m -l monochrome --description 'Force monochrome output.  See also --color.'
complete -c pinout -s x -l xyz --description 'Open \\%pinout. xyz <https://pinout. xyz/> in the default web browser.'
complete -c pinout -l ------ -l -- -l '-----\'' --description '.'

