# rngtest
# Autogenerated from man page /usr/share/man/man1/rngtest.1.gz
complete -c rngtest -s p -l pipe --description 'Enable pipe mode.'
complete -c rngtest -s c -l blockcount --description 'Exit after processing n input blocks, if n is not zero.'
complete -c rngtest -s b -l blockstats --description 'Dump statistics every n blocks, if n is not zero.'
complete -c rngtest -s t -l timedstats --description 'Dump statistics every n secods, if n is not zero.'
complete -c rngtest -s '?' -l help --description 'Give a short summary of all program options.'
complete -c rngtest -s V -l version --description 'Print program version.'

