# rpi-eeprom-update
# Autogenerated from man page /usr/share/man/man1/rpi-eeprom-update.1.gz
complete -c rpi-eeprom-update -s a --description '.'
complete -c rpi-eeprom-update -s A --description '.'
complete -c rpi-eeprom-update -s b --description '.'
complete -c rpi-eeprom-update -s d -s f --description 'flag use the config in that file.'
complete -c rpi-eeprom-update -s h --description '.'
complete -c rpi-eeprom-update -s i --description '.'
complete -c rpi-eeprom-update -s j -s m --description '.'
complete -c rpi-eeprom-update -s l --description 'to the FIRMWARE_RELEASE_STATUS and FIRMWARE_IMAGE_DIR settings.'
complete -c rpi-eeprom-update -s r --description 'cancels a pending update.'
complete -c rpi-eeprom-update -s s --description 'bootloader release is newer than the version specified by BOOTLOADER_AUTO_UPD…'
complete -c rpi-eeprom-update -s u --description 'ENVIRONMENT Environment variables should be defined in ,/etc/default/rpi-eepr…'

