# text2wave
# Autogenerated from man page /usr/share/man/man1/text2wave.1.gz
complete -c text2wave -o mode --description 'string.'
complete -c text2wave -s o --description 'ofile.'
complete -c text2wave -o otype --description 'string.'
complete -c text2wave -s f --description 'integer.'
complete -c text2wave -o scale --description 'float.'
complete -c text2wave -o eval --description 'string.'

